package com.paralex.erp.enums;

public enum EventType {
    VIRTUAL_ACCOUNT_CREATION,
    CUSTOMER_CREATION,
    PAYSTACK_WEBHOOK,
    PAYSTACK_TRANSFER_OUT,
    PAYSTACK_INIT_TRANSFER,
    PAYSTACK_INIT_TRANSACTION_BILL,
    PAYSTACK_VERIFY_TRANSACTION_BILL,
    PAYSTACK_TRANSFER_IN
}
